### ISSUE TITLE
prepare-tool: install tool base deps as root

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#121]
Add a `prepare-tool` to install all required distro base dependencies (apt).

**Comment by viceice** [comment]
@Chumper i think this has high priority, so we can dynamic install for tools like python, dotnet ...

**Comment by viceice** [comment]
They depends on some libraries which are installed via apt

**Comment by Chumper** [comment]
I am not exactly sure, that the `prepare-tool` should do.
Are you talking about a new script, that will install e.g. `bazaar` for golang in the image, so that go can be installed at runtime?

In that case would you do it similar to the installation of tools?
That we have a `prepare` folder with scripts for each tool that installs certain apt packages?
Or would you rather put that into one `prepare-tool` file that will do this for all tools?

**Comment by viceice** [comment]
closing, as it's now implemented and working for erlang
