### ISSUE TITLE
Cache dir / volume

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#197]
We should support an optional cache dir /volume to cache downloads, so we can mount a host volume / docker volume and reuse downloads to speedup later runs.

So Cache will be enabled if `BUILDPACK_CACHE` points to an existing folder.

**Comment by Chumper** [comment]
This would be high on my priority list, so that I can move to k8s with persistent volumes.
This would require an adjustment on all tools correct?

My idea for tool installation is:
* check if tool is in cache (e.g. `go${GOLANG_FILE_VERSION}.linux-amd64.tar.gz`)
* If not, download it into the cache folder
* Extract the binary from the cache folder

That would require all tools to download their dependencies into the cache. 
Or more abstract we create a `download` method that tools use.
Internally we will check the cache first and download the file if needed then return it.

**Comment by viceice** [comment]
Sounds good, but cache should only be used when explicit enabled. But feel free to open a draft PR for a single tool, so we can go forward on this.

**Comment by rarkins** [comment]
Is your primary concern bandwidth, or something else?

**Comment by Chumper** [comment]
yeah, my primary concern is bandwith, especially because we have a high number of javascript, python and go repositories.
If we would download the tools every time, that would be a bad idea. 
We as a company already create a lot of traffic for certain package registries, so I am trying to cache as much as possible.

It is not in the scale of the open source app you maintain, but its already a bit with around 500 onboarded repos atm.
