### ISSUE TITLE
Run `update-ca-certificates` if `/usr/local/share/ca-certificates/` contains any `*.crt`

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#53]
`install-buildpack` should check if there are any `*.crt` files in `/usr/local/share/ca-certificates/` and if so then run `update-ca-certificates` automatically.

**Comment by viceice** [comment]
Ha, `update-ca-certificates` is alread called by `install-buildpack`, because ti installs `ca-certificates`  and an install hook calls `update-ca-certificates`. So if the base image not already has `ca-certificates` it works already. 🎉 

With #95 it will also work if a custom base image already has `ca-certificates` 🙃
